# Generated by Django 5.1 on 2024-09-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_user_role_customer_receptionist_systemadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bookingID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
