# Generated by Django 5.1 on 2024-09-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_alter_customer_bookingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionist',
            name='hotelID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
