# Generated by Django 5.1 on 2024-09-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_hotel_tags_hotel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.FileField(null=True, upload_to='hotel_gallery'),
        ),
    ]
